### ISSUE TITLE
Feature request: add toggle or remove automatic padding below heading list.

### ISSUE THREAD

**Issue by jmonroynieto** [zhouhua/obsidian-sticky-headings#20]
I was trying to reduce the amount of padding between a stylized heading list and found that the value is programmatically set causing the value to shift as you scroll. I find it a bit distracting and would like to put in a set value.

![image1](https://github.com/user-attachments/assets/e68fdafd-4b74-4353-ae63-3535a539e5d5)

Using the developer tools, I enabled a "break on attribute change" for the padding value of interest. The line causing the issue is https://github.com/zhouhua/obsidian-sticky-headings/blob/7f103667e684a3b0258ab40c4bc761fd7acd4e48/src/Plugin.ts#L241

I don't know about other users, therefore the least disruptive implementation of a change would be to have a setting for it in the plugin configuration allowing us to disable automatic recalculation. It could be a value capture; when set to 0, people retain the automatic padding. Otherwise, the value is set in pixels.

**Comment by jmonroynieto** [comment]
This is my CSS rule to replicate the above style changes:
```css
.sticky-headings-root {
      transition: height 0.25s ease-in-out;
    background-color: #101818;
    border-radius: 12px;
    width: 40%;
    margin: auto;
    left: 0px;
    right: 0px;
    position: inherit;
    padding-top: 3px;
    padding-bottom: 4px;
}
```
