### ISSUE TITLE
Appreciation post

### ISSUE THREAD

**Issue by jmonroynieto** [zhouhua/obsidian-sticky-headings#34]
Thanks for the amazing work that led to the latest improvements. I am quite enjoying the floating theme. I just updated after my initial installation a few months ago, in a couple of minutes I had it just the way I wanted. Your changes made it very easy to send the pill to the bottom of the editor leaving the top space for reading and the search bar (example below).

On a related note, as a polite request, can we please get a short changelog or phrase for the releases so we know what to expect when you put out new versions?

![image](https://github.com/user-attachments/assets/a5a50e9e-c4d7-47ac-9f27-052f76da9988)

And here is the incredibly short CSS snippet that meshes the pill with my theme.

```css
.sticky-headings-container {
  --sticky-header-float-background-color: #101818;
    border-radius: 11px !important;
    bottom: 10px;
    position: fixed;
    box-shadow: inset 0 0 5px #D6BA7C;
}
```

Awesome work!
